server:
  port: 8761

spring:
  application:
    name: discovery

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

eureka:
  instance:
    hostname: ${eureka.hostname}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: ${eureka.default-zone}
